services:
  openvpn-main-udp:
    image: imkolganov/openvpn-gate-monitor-openvpn:latest
    pull_policy: always
    container_name: openvpn-main-udp
    restart: unless-stopped
    networks:
      - backend_network
    cap_add:
      - NET_ADMIN
    devices:
      - "/dev/net/tun:/dev/net/tun"
    volumes:
      - openvpn_data_main_udp:/openvpn-main-udp
    ports:
      - "1295:1295/udp"
      - "5009:5009"
    environment:
      EASY_RSA_PATH: "/openvpn-main-udp/easy-rsa"
      DATA_DIR: /openvpn-main-udp
      PORT: "1295"
      API_PORT: 5009
      PROTO: udp
      OpenVpnManagement__Port: "5095"
      OpenVpnManagement__Host: "localhost"
      BACKEND__BASEURL: "http://localhost:5581/"

networks:
  openvpn_network:
    driver: bridge
  backend_network:
    driver: bridge

volumes:
  openvpn_data_main_udp: