#!/bin/bash
set -e

PORT=${PORT:-1194}
PROTO=${PROTO:-udp}
OpenVpnManagement__Port=${OpenVpnManagement__Port:-5092}
DATA_DIR=${DATA_DIR:-/mnt}
DNS1=${DNS1:-8.8.8.8}
DNS2=${DNS2:-8.8.4.4}
VPN_SUBNET=${VPN_SUBNET:-10.51.28.0}
VPN_NETMASK=${VPN_NETMASK:-255.255.255.0}
EASYRSA_DIR="$DATA_DIR/easy-rsa"
CERT_SOURCE="/app/certs"

echo "===== STARTING OPENVPN CONTAINER ====="

echo "===== Checking for pre-generated certificates in $CERT_SOURCE ====="
USE_PREEXISTING_CERTS=false
MISSING_CERTS=()

for FILE in ca.crt server.crt server.key ta.key; do
    if [ ! -f "$CERT_SOURCE/$FILE" ]; then
        MISSING_CERTS+=("$FILE")
    fi
done

if [ ${#MISSING_CERTS[@]} -eq 0 ]; then
    echo "📦 All required pre-generated certs found:"
    ls -l "$CERT_SOURCE"
    USE_PREEXISTING_CERTS=true
else
    echo "⚠️ Missing the following certs in $CERT_SOURCE:"
    for FILE in "${MISSING_CERTS[@]}"; do
        echo "  ❌ $FILE"
    done
    echo "🛠️ Will generate new certs and keys including ta.key"
fi

# Enable IP forwarding
iptables -P FORWARD ACCEPT
iptables -A FORWARD -i tun0 -j ACCEPT
iptables -A FORWARD -o tun0 -j ACCEPT
iptables -t nat -A POSTROUTING -s 10.51.28.0/24 -o eth0 -j MASQUERADE

echo "===== Checking contents of $DATA_DIR before starting..."
ls -l "$DATA_DIR"

if [ "$USE_PREEXISTING_CERTS" = true ]; then
    echo "Copying certs from $CERT_SOURCE..."
    mkdir -p /etc/openvpn
    mkdir -p "$EASYRSA_DIR/pki"
    mkdir -p "$EASYRSA_DIR/pki/issued"
    mkdir -p "$EASYRSA_DIR/pki/private"

    cp "$CERT_SOURCE/ca.crt"        /etc/openvpn/ca.crt                    && echo "✅ Copied ca.crt"
    cp "$CERT_SOURCE/server.crt"    /etc/openvpn/server.crt                && echo "✅ Copied server.crt"
    cp "$CERT_SOURCE/server.key"    /etc/openvpn/server.key                && echo "✅ Copied server.key"
    cp "$CERT_SOURCE/ta.key"        /etc/openvpn/ta.key                    && echo "✅ Copied ta.key"

    # ✨ Also duplicate to EASYRSA_DIR/pki as if they were generated by Easy-RSA
    cp "$CERT_SOURCE/ca.crt"        "$EASYRSA_DIR/pki/ca.crt"              && echo "✅ Duplicated ca.crt to PKI"
    cp "$CERT_SOURCE/server.crt"    "$EASYRSA_DIR/pki/issued/server.crt"   && echo "✅ Duplicated server.crt to PKI"
    cp "$CERT_SOURCE/server.key"    "$EASYRSA_DIR/pki/private/server.key"  && echo "✅ Duplicated server.key to PKI"
    cp "$CERT_SOURCE/ta.key"        "$EASYRSA_DIR/pki/ta.key"              && echo "✅ Duplicated ta.key to PKI"

    [ -f "$CERT_SOURCE/crl.pem" ] && cp "$CERT_SOURCE/crl.pem" "$EASYRSA_DIR/pki/crl.pem" && echo "✅ Copied crl.pem"
else
    # Copy Easy-RSA templates
    if [ ! -x "$EASYRSA_DIR/easyrsa" ]; then
        echo "Copying Easy-RSA to $EASYRSA_DIR..."
        mkdir -p "$EASYRSA_DIR"
        cp -r /usr/share/easy-rsa/* "$EASYRSA_DIR"
        chmod +x "$EASYRSA_DIR/easyrsa"
    fi

    cd "$EASYRSA_DIR"
    export EASYRSA_BATCH=1
    export EASYRSA_REQ_CN="OpenVPN-Server"
    export EASYRSA_PKI="$EASYRSA_DIR/pki"

    ./easyrsa init-pki
    ./easyrsa build-ca nopass
    ./easyrsa gen-req server nopass
    ./easyrsa sign-req server server
    openvpn --genkey secret "$EASYRSA_DIR/pki/ta.key"
    ./easyrsa gen-crl
    chmod 644 "$EASYRSA_DIR/pki/crl.pem"

    mkdir -p /etc/openvpn
    cp "$EASYRSA_DIR/pki/ca.crt"              /etc/openvpn/ca.crt      && echo "✅ Copied ca.crt (generated)"
    cp "$EASYRSA_DIR/pki/issued/server.crt"   /etc/openvpn/server.crt  && echo "✅ Copied server.crt (generated)"
    cp "$EASYRSA_DIR/pki/private/server.key"  /etc/openvpn/server.key  && echo "✅ Copied server.key (generated)"
    cp "$EASYRSA_DIR/pki/ta.key"              /etc/openvpn/ta.key      && echo "✅ Copied ta.key (generated)"
fi

# Copy certs to final location
echo "===== Final cert copy to /etc/openvpn... ====="
declare -A FILES_TO_COPY=(
  ["$EASYRSA_DIR/pki/ca.crt"]="/etc/openvpn/ca.crt"
  ["$EASYRSA_DIR/pki/issued/server.crt"]="/etc/openvpn/server.crt"
  ["$EASYRSA_DIR/pki/private/server.key"]="/etc/openvpn/server.key"
  ["$EASYRSA_DIR/pki/ta.key"]="/etc/openvpn/ta.key"
)

for SRC in "${!FILES_TO_COPY[@]}"; do
  DEST=${FILES_TO_COPY[$SRC]}
  if [ -f "$SRC" ]; then
    cp "$SRC" "$DEST"
    echo "✅ Confirmed & copied $SRC → $DEST"
  else
    echo "❌ ERROR: Required file $SRC not found, exiting."
    exit 1
  fi
done

# Generate default server.conf if not present
if [ ! -f "$DATA_DIR/server.conf" ]; then
    echo "Generating default server.conf..."
    cat <<EOF > "$DATA_DIR/server.conf"
port $PORT
proto $PROTO
dev tun

ca /etc/openvpn/ca.crt
cert /etc/openvpn/server.crt
key /etc/openvpn/server.key
dh none
tls-groups prime256v1

topology subnet
server $VPN_SUBNET $VPN_NETMASK
ifconfig-pool-persist /etc/openvpn/ipp.txt

push "dhcp-option DNS $DNS1"
push "dhcp-option DNS $DNS2"
push "block-outside-dns"
push "redirect-gateway def1"

keepalive 15 120

remote-cert-tls client
tls-version-min 1.2
tls-crypt /etc/openvpn/ta.key

cipher AES-256-CBC
auth SHA256

user nobody
group nogroup

persist-key
persist-tun

crl-verify $EASYRSA_DIR/pki/crl.pem

status $DATA_DIR/openvpn-status.log
status-version 3
log $DATA_DIR/openvpn.log
log-append $DATA_DIR/openvpn.log
syslog

management 127.0.0.1 $OpenVpnManagement__Port

verb 4
EOF
fi

# Logs
echo "Clearing logs..."
truncate -s 0 "$DATA_DIR/openvpn.log" || touch "$DATA_DIR/openvpn.log"
truncate -s 0 "$DATA_DIR/openvpn-status.log" || touch "$DATA_DIR/openvpn-status.log"
chmod 777 "$DATA_DIR/openvpn.log" "$DATA_DIR/openvpn-status.log"

# Ensure CRL
if [ ! -f "$EASYRSA_DIR/pki/crl.pem" ]; then
    echo "Generating crl.pem (empty revocation list)..."
    cd "$EASYRSA_DIR"
    export EASYRSA_PKI="$EASYRSA_DIR/pki"
    ./easyrsa gen-crl
else
    echo "crl.pem already exists."
fi
chmod 644 "$EASYRSA_DIR/pki/crl.pem"

# Set read and execute permissions for DATA_DIR
echo "Setting permissions for $DATA_DIR recursively..."
chmod -R a+rX "$DATA_DIR"

echo "===== FINAL CHECK BEFORE STARTING OPENVPN ====="
ls -l "$DATA_DIR"
[ -d "$EASYRSA_DIR/pki" ] && ls -l "$EASYRSA_DIR/pki"

# Show config
{ sleep 0.1; echo "===== server.conf contents ====="; cat "$DATA_DIR/server.conf"; } &

# Launch OpenVPN
echo "===== Starting OpenVPN in background... ====="
openvpn --config "$DATA_DIR/server.conf" &
OPENVPN_PID=$!

# Wait for .NET app
echo "[entrypoint] Starting .NET application..."

# Wait for .NET files
echo "⏳ Waiting for DataGateCertManager.dll and dependencies to appear..."
timeout=10
elapsed=0

while [ ! -f /app/DataGateCertManager.dll ] || [ ! -f /app/DataGateCertManager.runtimeconfig.json ]; do
    if [ "$elapsed" -ge "$timeout" ]; then
        echo "❌ ERROR: .NET files not found after ${timeout}s, exiting"
        echo "🔍 /app contents:"
        ls -la /app
        exit 1
    fi
    echo "  ...still waiting (${elapsed}s)"
    sleep 1
    elapsed=$((elapsed + 1))
done

echo "✅ Found required .NET files"
cd /app
dotnet DataGateCertManager.dll &
DOTNET_PID=$!

wait $OPENVPN_PID
OPENVPN_EXIT_CODE=$?

wait $DOTNET_PID
DOTNET_EXIT_CODE=$?

if [ $OPENVPN_EXIT_CODE -ne 0 ]; then
  echo "OpenVPN exited with code $OPENVPN_EXIT_CODE"
  exit $OPENVPN_EXIT_CODE
fi

if [ $DOTNET_EXIT_CODE -ne 0 ]; then
  echo ".NET app exited with code $DOTNET_EXIT_CODE"
  exit $DOTNET_EXIT_CODE
fi