script-security 2
client-connect /etc/openvpn/scripts/client-connect.sh
client-disconnect /etc/openvpn/scripts/client-disconnect.sh
learn-address /etc/openvpn/scripts/learn-address.sh
tls-verify /etc/openvpn/scripts/tls-verify.sh
